-- fnctl:statement
CREATE TABLE IF NOT EXISTS `validation_queue` (
  `validation_job_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '验证任务内部主键',
  `node_config_id` BIGINT UNSIGNED NOT NULL COMMENT '待验证节点配置主键',
  `stage` VARCHAR(32) NOT NULL COMMENT '验证阶段',
  `priority` SMALLINT NOT NULL DEFAULT 0 COMMENT '任务优先级',
  `job_state` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '任务状态',
  `attempts` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务领取次数',
  `max_attempts` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务最大尝试次数零为不限',
  `next_attempt_at` DATETIME(6) NOT NULL COMMENT '下次允许执行时间',
  `lease_owner` VARCHAR(255) NULL COMMENT '当前租约所有者',
  `leased_until` DATETIME(6) NULL COMMENT '当前租约到期时间',
  `last_error_code` VARCHAR(64) NULL COMMENT '最近稳定错误码',
  `last_error_summary` VARCHAR(1024) NULL COMMENT '最近受限错误摘要',
  `completed_at` DATETIME(6) NULL COMMENT '最近完成时间',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (`validation_job_id`),
  UNIQUE KEY `uk_validation_queue_node_stage` (`node_config_id`, `stage`),
  KEY `idx_validation_queue_claim` (`job_state`, `next_attempt_at`, `leased_until`, `priority`),
  KEY `idx_validation_queue_owner` (`lease_owner`, `leased_until`),
  KEY `idx_validation_queue_completed` (`completed_at`),
  CONSTRAINT `fk_validation_queue_node` FOREIGN KEY (`node_config_id`) REFERENCES `node_configs` (`node_config_id`) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='可恢复的持久验证任务队列';

-- fnctl:statement
CREATE TABLE IF NOT EXISTS `validation_batches` (
  `validation_batch_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '验证批次内部主键',
  `validator_id` VARCHAR(255) NOT NULL COMMENT '验证机唯一标识',
  `stage` VARCHAR(32) NOT NULL COMMENT '批次验证阶段',
  `engine` VARCHAR(64) NOT NULL COMMENT '验证执行引擎',
  `engine_version` VARCHAR(64) NULL COMMENT '验证引擎版本',
  `config_snapshot` JSON NOT NULL COMMENT '脱敏后的批次配置快照',
  `started_at` DATETIME(6) NOT NULL COMMENT '批次开始时间',
  `finished_at` DATETIME(6) NULL COMMENT '批次结束时间',
  `claimed_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '领取任务数量',
  `success_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功任务数量',
  `partial_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '部分成功任务数量',
  `failure_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败任务数量',
  `batch_state` VARCHAR(32) NOT NULL COMMENT '批次状态',
  `error_summary` VARCHAR(1024) NULL COMMENT '批次受限错误摘要',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  PRIMARY KEY (`validation_batch_id`),
  KEY `idx_validation_batches_validator_time` (`validator_id`, `started_at`),
  KEY `idx_validation_batches_state` (`batch_state`, `started_at`)
) ENGINE=InnoDB COMMENT='验证工作批次';

-- fnctl:statement
CREATE TABLE IF NOT EXISTS `validation_attempts` (
  `validation_attempt_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '单次验证内部主键',
  `validation_job_id` BIGINT UNSIGNED NULL COMMENT '关联验证任务主键',
  `validation_batch_id` BIGINT UNSIGNED NULL COMMENT '关联验证批次主键',
  `node_config_id` BIGINT UNSIGNED NOT NULL COMMENT '被验证节点配置主键',
  `validator_id` VARCHAR(255) NOT NULL COMMENT '验证机唯一标识',
  `stage` VARCHAR(32) NOT NULL COMMENT '本次验证阶段',
  `round_number` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '多轮验证轮次',
  `started_at` DATETIME(6) NOT NULL COMMENT '验证开始时间',
  `finished_at` DATETIME(6) NULL COMMENT '验证结束时间',
  `config_accepted` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '客户端是否接受配置',
  `proxy_started` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '代理进程是否启动',
  `passed` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否完全验证成功',
  `partial_success` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否部分目标成功',
  `target_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '验证目标数量',
  `success_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功目标数量',
  `dns_ms` INT UNSIGNED NULL COMMENT 'DNS耗时毫秒',
  `connect_ms` INT UNSIGNED NULL COMMENT '连接耗时毫秒',
  `tls_ms` INT UNSIGNED NULL COMMENT 'TLS握手耗时毫秒',
  `proxy_start_ms` INT UNSIGNED NULL COMMENT '代理启动耗时毫秒',
  `ttfb_ms` INT UNSIGNED NULL COMMENT '首字节耗时毫秒',
  `total_ms` INT UNSIGNED NULL COMMENT '请求总耗时毫秒',
  `http_median_ms` INT UNSIGNED NULL COMMENT '成功目标延迟中位数毫秒',
  `performance_bytes` BIGINT UNSIGNED NULL COMMENT '性能采样读取字节数',
  `bytes_per_second` BIGINT UNSIGNED NULL COMMENT '性能采样每秒字节数',
  `exit_ip` VARCHAR(45) NULL COMMENT '验证观察到的出口IP',
  `exit_country` CHAR(2) NULL COMMENT '出口国家代码',
  `exit_asn` VARCHAR(32) NULL COMMENT '出口自治系统编号',
  `target_results` JSON NULL COMMENT '各验证目标结构化结果',
  `error_code` VARCHAR(64) NULL COMMENT '稳定验证错误码',
  `error_summary` VARCHAR(1024) NULL COMMENT '受限长度错误摘要',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  PRIMARY KEY (`validation_attempt_id`),
  KEY `idx_validation_attempts_node_time` (`node_config_id`, `started_at`),
  KEY `idx_validation_attempts_validator_time` (`validator_id`, `started_at`),
  KEY `idx_validation_attempts_result_time` (`passed`, `started_at`),
  KEY `idx_validation_attempts_cleanup` (`finished_at`),
  CONSTRAINT `fk_validation_attempts_job` FOREIGN KEY (`validation_job_id`) REFERENCES `validation_queue` (`validation_job_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_validation_attempts_batch` FOREIGN KEY (`validation_batch_id`) REFERENCES `validation_batches` (`validation_batch_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_validation_attempts_node` FOREIGN KEY (`node_config_id`) REFERENCES `node_configs` (`node_config_id`) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='每次节点验证的详细结果';

-- fnctl:statement
CREATE TABLE IF NOT EXISTS `node_current_status` (
  `node_config_id` BIGINT UNSIGNED NOT NULL COMMENT '节点配置主键',
  `lifecycle_state` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '当前生命周期状态',
  `availability_state` VARCHAR(32) NOT NULL DEFAULT 'unverified' COMMENT '当前可用性状态',
  `quality_score` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前综合质量分',
  `quality_grade` CHAR(1) NOT NULL DEFAULT 'U' COMMENT '当前质量等级',
  `score_breakdown` JSON NULL COMMENT '各评分维度明细',
  `last_validation_at` DATETIME(6) NULL COMMENT '最近验证时间',
  `last_success_at` DATETIME(6) NULL COMMENT '最近成功时间',
  `last_failure_at` DATETIME(6) NULL COMMENT '最近失败时间',
  `success_rate_1d` DECIMAL(6,3) NULL COMMENT '最近一日成功率',
  `success_rate_7d` DECIMAL(6,3) NULL COMMENT '最近七日成功率',
  `success_rate_30d` DECIMAL(6,3) NULL COMMENT '最近三十日成功率',
  `latency_p50_ms` INT UNSIGNED NULL COMMENT '延迟中位数毫秒',
  `latency_p95_ms` INT UNSIGNED NULL COMMENT '延迟第九十五百分位毫秒',
  `source_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '独立活跃来源数量',
  `consecutive_successes` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '连续成功次数',
  `consecutive_failures` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '连续失败次数',
  `exit_ip` VARCHAR(45) NULL COMMENT '最近出口IP',
  `exit_country` CHAR(2) NULL COMMENT '最近出口国家代码',
  `exit_asn` VARCHAR(32) NULL COMMENT '最近出口自治系统编号',
  `last_error_code` VARCHAR(64) NULL COMMENT '最近稳定错误码',
  `last_error_summary` VARCHAR(1024) NULL COMMENT '最近受限错误摘要',
  `next_check_at` DATETIME(6) NULL COMMENT '下次计划验证时间',
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (`node_config_id`),
  KEY `idx_node_current_export` (`availability_state`, `quality_grade`, `last_success_at`),
  KEY `idx_node_current_next_check` (`next_check_at`),
  KEY `idx_node_current_grade_score` (`quality_grade`, `quality_score`),
  CONSTRAINT `fk_node_current_status_node` FOREIGN KEY (`node_config_id`) REFERENCES `node_configs` (`node_config_id`) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='每个节点的最新验证和质量状态';

-- fnctl:statement
CREATE TABLE IF NOT EXISTS `node_daily_stats` (
  `node_daily_stat_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '节点每日统计内部主键',
  `stat_date` DATE NOT NULL COMMENT '统计日期',
  `node_config_id` BIGINT UNSIGNED NOT NULL COMMENT '节点配置主键',
  `validation_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日验证次数',
  `success_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日成功次数',
  `partial_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日部分成功次数',
  `failure_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日失败次数',
  `success_rate` DECIMAL(6,3) NOT NULL DEFAULT 0 COMMENT '当日验证成功率',
  `latency_p50_ms` INT UNSIGNED NULL COMMENT '当日延迟中位数毫秒',
  `latency_p95_ms` INT UNSIGNED NULL COMMENT '当日延迟第九十五百分位毫秒',
  `max_success_streak` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日最长连续成功次数',
  `source_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日活跃来源数量',
  `quality_score` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日最终质量分',
  `quality_grade` CHAR(1) NOT NULL DEFAULT 'U' COMMENT '当日最终质量等级',
  `exit_ips` JSON NULL COMMENT '当日观察到的出口IP集合',
  `error_counts` JSON NULL COMMENT '当日错误分类计数',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
  PRIMARY KEY (`node_daily_stat_id`),
  UNIQUE KEY `uk_node_daily_stats_date_node` (`stat_date`, `node_config_id`),
  KEY `idx_node_daily_stats_node_date` (`node_config_id`, `stat_date`),
  KEY `idx_node_daily_stats_grade_date` (`quality_grade`, `stat_date`),
  CONSTRAINT `fk_node_daily_stats_node` FOREIGN KEY (`node_config_id`) REFERENCES `node_configs` (`node_config_id`) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='节点验证和质量每日永久汇总';
